### ISSUE TITLE
[Bug Report] Build failed when user doesn't create files for directory classifier.

### ISSUE THREAD

**Issue by ulivz** [ulivz/vuepress-plugin-blog#1]
## Error

```js
Rendering page: /archive/[Vue warn]: Error in render: "TypeError: Cannot read property 'interval' of undefined"

found in

---> <BaseListLayout>
       <Layout>
         <Anonymous>
           <Root>
error Error rendering /archive/: false
undefined
TypeError: Cannot read property 'interval' of undefined
```

## Workaround

```js
module.exports = {
  theme: '@vuepress/blog',
  themeConfig: {
    modifyBlogPluginOptions(blogPlugnOptions) {
      const archiveDirectoryClassifierIndex = blogPlugnOptions.directories.findIndex(d => d.id === 'archive')
      blogPlugnOptions.directories.splice(archiveDirectoryClassifierIndex, 1)
      return blogPlugnOptions
    },
}
```

**Comment by ulivz** [comment]
Temporarily fixed at https://github.com/ulivz/vuepress-theme-blog/commit/5a34e26d907210e3f48f59566a0d26757ec76805

**Comment by ulivz** [comment]
Fixed at https://github.com/ulivz/vuepress-plugin-blog/commit/d64964d9953da4240985fc71a102f5dc11051d45 from the root.

**Comment by raisty** [comment]
Bug still occurs while using GitHub Actions.
https://github.com/vuepress/vuepress-theme-blog/issues/106
